import { Component, Project } from 'projen';
import { TextFile } from 'projen/lib/textfile';

export interface AgentConfigurationOptions {

}

export class AgentConfiguration extends Component {
  constructor(project: Project, _options: AgentConfigurationOptions) {
    super(project);

    this.project.addGitIgnore('.scratch');

    new TextFile(this.project, 'AGENTS.md', {
      lines: [
        '# Agent Configuration',
        '',
        '// Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".',
        '',
        'This file configures how agent skills interact with this repository.',
        '',
        '## Agent skills',
        '',
        '### Issue tracker',
        '',
        'Issues are tracked as markdown files under `.scratch/<feature>/` in this repo. See `docs/agents/issue-tracker.md`.',
        '',
        '### Triage labels',
        '',
        'Uses default label vocabulary: needs-triage, needs-info, ready-for-agent, ready-for-human, wontfix. See `docs/agents/triage-labels.md`.',
        '',
        '### Domain docs',
        '',
        'Single-context layout with `CONTEXT.md` at the repo root and ADRs in `docs/adr/`. See `docs/agents/domain.md`.',
        '',
      ],
    });

    new TextFile(this.project, 'docs/agents/issue-tracker.md', {
      lines: [
        '# Issue tracker',
        '',
        '// Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".',
        '',
        'We use a local markdown-based issue tracker.',
        '',
        'New issues are created as markdown files under `.scratch/<feature>/<issue>.md`.',
        '',
        'Each issue file should include metadata at the top for triage tracking:',
        '',
        '```markdown',
        '---',
        'status: needs-triage  # One of: needs-triage, needs-info, ready-for-agent, ready-for-human, wontfix',
        'title: Feature request',
        '---',
        '```',
        '',
        '## External PRs as a request surface',
        '',
        'Not applicable — we are using a local markdown issue tracker.',
        '',
      ],
    });

    new TextFile(this.project, 'docs/agents/triage-labels.md', {
      lines: [
        '# Triage labels',
        '',
        '// Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".',
        '',
        'The five canonical triage roles and the strings they map to in our issue tracker:',
        '',
        '| Role | Label | Description |',
        '|------|-------|-------------|',
        '| needs-triage | `needs-triage` | Maintainer needs to evaluate |',
        '| needs-info | `needs-info` | Waiting on reporter |',
        '| ready-for-agent | `ready-for-agent` | Fully specified, AFK-ready (an agent can pick it up with no human context) |',
        '| ready-for-human | `ready-for-human` | Needs human implementation |',
        '| wontfix | `wontfix` | Will not be actioned |',
        '',
      ],
    });

    new TextFile(this.project, 'docs/agents/domain.md', {
      lines: [
        '# Domain docs',
        '',
        '// Generated by projen. To modify, edit .projenrc.ts and run "pnpm exec projen".',
        '',
        '## Layout',
        '',
        'Single-context: one `CONTEXT.md` at the repo root, with ADRs in `docs/adr/`.',
        '',
        '## Consumer rules',
        '',
        'When skills need to understand the project\'s domain:',
        '',
        '1. **Read `CONTEXT.md` first** — this contains the project\'s ubiquitous language, domain terminology, and high-level architecture',
        '2. **Check `docs/adr/`** — past architectural decisions (ADRs) that explain why certain design choices were made',
        '',
        '## Creating ADRs',
        '',
        'When making a significant architectural decision:',
        '',
        '1. Create a new file in `docs/adr/` following the pattern `YYYY-MM-DD-<description>.md`',
        '2. Include the decision context, options considered, and the chosen approach',
        '3. Reference related ADRs if applicable',
        '',
      ],
    });

    new TextFile(this.project, 'CONTEXT.md', {
      lines: [
        '# Project Context',
        '',
        '> **Agent Instructions**: This file should be filled out by an agent or maintainer. Replace the content below with actual project-specific information. See the guidelines in `docs/agents/domain.md` for what to include.',
        '',
        '## Instructions for Agent',
        '',
        'Please populate this file with the following sections:',
        '',
        '### 1. Overview',
        '- Brief description of what this project is and its purpose',
        '',
        '### 2. Domain Terminology',
        '- Table of domain-specific terms and their definitions',
        '- Include project-specific jargon, acronyms, and concepts',
        '',
        '### 3. Architecture',
        '- High-level architecture overview',
        '- Key components and how they interact',
        '- Technology stack (language, framework, databases, etc.)',
        '',
        '### 4. Project Structure',
        '- Description of the repository structure',
        '- Purpose of key directories',
        '- Important files and their roles',
        '',
        '### 5. Key Dependencies',
        '- Major dependencies and their purpose',
        '- Any notable version constraints',
        '',
        '### 6. Development Workflow',
        '- How to set up the development environment',
        '- Common commands (build, test, run, etc.)',
        '- Any special workflow considerations',
        '',
        '### 7. Related Documentation',
        '- Links to ADRs (Architectural Decision Records)',
        '- Links to external documentation',
        '',
        '---',
        '',
        '*This template will be replaced with actual content. Delete this instruction block once filled out.*',
        '',
      ],
      readonly: false,
    });
  }
}
